image: python:3.10

# Define stages for the pipeline.
stages:
  - test

# Define the job to run tests.
test:
  stage: test
  script:
    # Install dependencies (if needed)
    - pip install pytest pytest-cov junit-xml

    # Run pytest with HTML report generation
    - pytest --cov=Day_01_2021 --cov=Day_02_2021 --cov-report=html:junit-coverage.xml

  artifacts:
    paths:
     - junit-coverage.xml
